Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(f"""{arr1}

{arr2}

{np.add(arr1,arr2)}""")

[[0.5256957  0.59461321 0.21323555]
 [0.89189212 0.10784103 0.30887283]
 [0.36208129 0.14531431 0.9690151 ]]

[[0.12837206 0.85188216 0.48955532]
 [0.91572832 0.71294885 0.33909681]
 [0.48757328 0.03969203 0.04033127]]

[[0.65406775 1.44649537 0.70279087]
 [1.80762043 0.82078988 0.64796964]
 [0.84965457 0.18500634 1.00934637]]


Write a Python Program to Multiply Two Matrices?

In [10]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(f"""
array 1:
{arr1}

array 2
{arr2}

dot product
{np.dot(arr1,arr2)}

cross product
{np.cross(arr1,arr2)}""")


array 1:
[[0.46227934 0.97394948 0.06627979]
 [0.3339945  0.75422335 0.32806797]
 [0.41870124 0.18549526 0.29710089]]

array 2
[[0.39881916 0.27726591 0.97819873]
 [0.56075562 0.59454739 0.25680209]
 [0.67399758 0.92503494 0.87167673]]

dot product
[[0.77518592 0.76854454 0.76008788]
 [0.77725541 0.84450115 0.80636835]
 [0.47124887 0.501206   0.71618452]]

cross product
[[ 0.93433903 -0.42576741 -0.26025542]
 [-0.00136582  0.09819547 -0.22435942]
 [-0.1131368  -0.16472685  0.26228992]]


Write a Python Program to Transpose a Matrix?

In [11]:
import numpy as np
arr1=np.random.rand(3,3)
print(f"""
array1:
{arr1}

transpose matrix:
{np.transpose(arr1)}
""")
for i in arr1:
    for j in arr1[i]:
        arr1[i][j]


array1:
[[0.18228346 0.48435463 0.71052067]
 [0.96721838 0.08565827 0.32290115]
 [0.4558567  0.20084879 0.33865538]]

transpose matrix:
[[0.18228346 0.96721838 0.4558567 ]
 [0.48435463 0.08565827 0.20084879]
 [0.71052067 0.32290115 0.33865538]]



Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
Input_statement=input("Enter the statement u like to sort alphabetically: ")
Unsorted_list=[Get_words for Get_words in Input_statement.lower().split()]
Unsorted_list.sort()
print(Unsorted_list)

Enter the statement u like to sort alphabetically:  Enter the statement u like to sort alphabetically:


['alphabetically:', 'enter', 'like', 'sort', 'statement', 'the', 'to', 'u']


Write a Python Program to Remove Punctuation From a String?

In [ ]:
Input_statement="Enter (the {statement}), u like, to sort alphabetically. :"
punctuations_string='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
punctutation_free_string=str()
for letter in Input_statement:
    if letter not in punctuations_string:
        punctutation_free_string+=letter
print(punctutation_free_string)


Enter the statement u like to sort alphabetically 
